version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs

  api:
    image: olusammy/monie:latest
    restart: unless-stopped
    ports:
    - 3000:3000
    # command: npm run dv
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node dist/src/index.js'
    networks:  # Add this section
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge